string1 = input("please input string A : ")
string2 = input("Please input string B : ")
a = float(input("Please input A : "))
b = float(input("Please input B : "))
print("Result :")
print(string1 + string2)
print(a*b)